name: Scrape latest hospital data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '15 */1 * * *' # At minute 15 past every hour

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 gitpython sqlite-utils
      
      - name: Fetch latest data
        run: python scrape_hospital_data.py

      - name: Check if hospital_data.json has changed
        id: file_check
        run: |
          git diff --name-only | grep hospital_data.json && echo "::set-output name=changed::true" || echo "::set-output name=changed::false"

      - name: Copy hospital_data.json with timestamp if changed
        if: steps.file_check.outputs.changed == 'true'
        run: |
          mkdir -p data
          timestamp=$(date -u +'%Y%m%d%H%M%S')
          cp hospital_data.json data/hospital_data_${timestamp}.json
          git add data/hospital_data_${timestamp}.json
          echo "hospital_data.json copied with timestamp."

      - name: Commit and push if hospital_data.json changed
        if: steps.file_check.outputs.changed == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Update hospital_data.json with timestamp: ${timestamp}" -a || echo "No changes to commit"
          git push

